### ISSUE TITLE
Comparison to Heng's "seqtk sample" ?

### ISSUE THREAD

**Issue by tseemann** [dylanstorey/SubSampleFastq#1]
I only recently became aware of 

```
% seqtk sample

Usage:   seqtk sample [-2] [-s seed=11] <in.fa> <frac>|<number>
Options: -s INT       RNG seed [11]
         -2           2-pass mode: twice as slow but with much reduced memory
```

If you want to do paired files, you just use the same RNG seed for R1 and R2 and you'll get the corresponding pairs.

**Comment by dylanbstorey** [comment]
Clever. I'll probably implement it soon

**Comment by dylanbstorey** [comment]
Cause fixing this required a big change.
